<#
  sync-payload.ps1 -- refresh ModReady's vendored payload from a beta-deps build.

  ModReady bundles a SNAPSHOT of the four BUTR dependency modules + BLSE binaries
  in installer\payload\. This script re-copies them from a built beta-deps repo so
  the snapshot tracks the latest module DLLs. It deliberately EXCLUDES the BetaDeps
  framework module -- ModReady ships the dependency stack only.

  What it pulls:
    - The four dependency module folders  <- <BetaDepsRepo>\dist\Modules\
    - BLSE binaries                        <- <BlseDir> (flat folder of BLSE files)
    - BLSE MIT license + third-party notices <- beta-deps payload/dist

  Prerequisite: run <BetaDepsRepo>\scripts\Build-Phase1.ps1 first so dist\Modules
  is fresh.

  Usage:
    cd C:\dev\modready
    .\scripts\sync-payload.ps1
    .\scripts\sync-payload.ps1 -BetaDepsRepo C:\dev\beta-deps -BlseDir C:\dev\beta-deps\installer\payload\BLSE
#>

param(
  [string] $BetaDepsRepo = 'C:\dev\beta-deps',
  # Flat folder containing the BLSE binaries (Bannerlord.BLSE.LauncherEx.exe etc.).
  # Defaults to the BLSE staged inside the beta-deps installer payload.
  [string] $BlseDir = ''
)

$ErrorActionPreference = 'Stop'
$Repo    = Split-Path $PSScriptRoot -Parent
$Payload = Join-Path $Repo 'installer\payload'

function Fail($msg) { Write-Host "ERROR: $msg" -ForegroundColor Red; exit 1 }

$deps = 'Bannerlord.Harmony','Bannerlord.UIExtenderEx','Bannerlord.ButterLib','Bannerlord.MBOptionScreen'

# --- resolve sources ---------------------------------------------------------
$srcModules = Join-Path $BetaDepsRepo 'dist\Modules'
if (-not (Test-Path $srcModules)) {
  Fail "beta-deps dist\Modules not found at '$srcModules'. Run '$BetaDepsRepo\scripts\Build-Phase1.ps1' first."
}
if (-not $BlseDir) { $BlseDir = Join-Path $BetaDepsRepo 'installer\payload\BLSE' }
if (-not (Test-Path (Join-Path $BlseDir 'Bannerlord.BLSE.LauncherEx.exe'))) {
  Fail "BLSE binaries not found at '$BlseDir' (no Bannerlord.BLSE.LauncherEx.exe). Pass -BlseDir <folder of BLSE files>."
}

# --- rebuild payload\Modules (4 deps only) -----------------------------------
$payloadModules = Join-Path $Payload 'Modules'
if (Test-Path $payloadModules) { Remove-Item $payloadModules -Recurse -Force }
New-Item -ItemType Directory -Path $payloadModules | Out-Null
foreach ($m in $deps) {
  $src = Join-Path $srcModules $m
  if (-not (Test-Path $src)) { Fail "dist\Modules\$m missing in beta-deps -- rebuild it (Build-Phase1.ps1)." }
  Copy-Item $src $payloadModules -Recurse -Force
  Write-Host "  vendored Modules\$m" -ForegroundColor Cyan
}

# --- BLSE --------------------------------------------------------------------
$payloadBlse = Join-Path $Payload 'BLSE'
if (Test-Path $payloadBlse) { Remove-Item $payloadBlse -Recurse -Force }
New-Item -ItemType Directory -Path $payloadBlse | Out-Null
Copy-Item (Join-Path $BlseDir '*') $payloadBlse -Recurse -Force
Write-Host "  vendored BLSE binaries" -ForegroundColor Cyan

# --- license notices ---------------------------------------------------------
$payloadLic = Join-Path $Payload 'LICENSES'
if (Test-Path $payloadLic) { Remove-Item $payloadLic -Recurse -Force }
New-Item -ItemType Directory -Path $payloadLic | Out-Null

# BLSE MIT license (try a couple of common spots).
$blseLic = @(
  (Join-Path $BlseDir 'LICENSE'),
  (Join-Path $BlseDir 'LICENSE.txt'),
  (Join-Path $BetaDepsRepo 'installer\payload\LICENSES\BLSE-LICENSE.txt')
) | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $blseLic) { Fail "BLSE LICENSE not found (looked in '$BlseDir' and beta-deps payload). MIT requires shipping it." }
Copy-Item $blseLic (Join-Path $payloadLic 'BLSE-LICENSE.txt') -Force

# Third-party notices (Harmony/Cecil/MonoMod/Newtonsoft) generated by Build-Phase1.
$tpl = Join-Path $srcModules 'BetaDeps\THIRD-PARTY-LICENSES.txt'
if (-not (Test-Path $tpl)) {
  Fail "Third-party notices not found at '$tpl'. They are REQUIRED (Harmony/Cecil/MonoMod/Newtonsoft ship inside the deps). Run Build-Phase1.ps1."
}
Copy-Item $tpl (Join-Path $payloadLic 'BetaDeps-THIRD-PARTY-LICENSES.txt') -Force
Write-Host "  vendored license notices" -ForegroundColor Cyan

# --- guard: BetaDeps framework module must NOT be vendored -------------------
if (Test-Path (Join-Path $payloadModules 'BetaDeps')) {
  Fail "payload\Modules\BetaDeps was vendored by mistake -- ModReady ships the dependency stack only."
}

Write-Host "Payload synced: BLSE + 4 dependency modules (no BetaDeps module)." -ForegroundColor Green
